In [66]:
import numpy as np
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
import json

In [67]:
f = open("Eight_group_data.0000", "r")
Input = f.readlines()
f.close()

group_data = np.ones((len(Input),3))
for c, i in enumerate(Input):
    group = Input[c].split(" ")
    group_data[c,0] = float(group[0])
    group_data[c,1] = float(group[1])
    group_data[c,2] = float(group[2])

In [68]:
print(group_data)

[[0.0056 0.0134 0.3507]
 [0.0029 0.0056 0.4105]
 [0.0025 0.0011 0.2388]
 [0.0133 0.0067 0.    ]
 [0.0473 0.022  0.    ]
 [0.018  0.0222 0.    ]
 [0.0558 0.0897 0.    ]
 [0.1798 0.2141 0.    ]]


In [71]:
g = open("Eight_group_scattering.000", "r")
Input2 = g.readlines()
g.close()


scat_list = []
for i in range(len(Input2)):
    scat_list.append(Input2[i].split(" "))
scat_data = np.zeros((len(Input),len(scat_list[0])))
for i in range(len(scat_list)):
    for j in range(len(scat_list[0])):
        scat_data[i,j] = float(scat_list[i][j])

In [72]:
print(scat_data)

[[1.1790e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00]
 [5.3000e-02 1.9490e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00]
 [3.0100e-02 1.1590e-01 5.8680e-01 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00]
 [1.0000e-04 5.0000e-04 7.6900e-02 8.2340e+03 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.9000e-03 1.9610e-01 8.1800e-01 0.0000e+00
  0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 5.0000e-03 1.7370e-01 6.9020e-01
  2.3000e-03 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 7.0000e-04 2.4600e-02 2.7070e-01
  8.6260e-01 2.7500e-02]
 [0.0000e+00 0.0000e+00 0.0000e+00 1.0000e-04 7.3000e-03 5.5000e-02
  3.5890e-01 1.9761e+00]]


In [84]:
def Create_fission_matrix(group_data):
    dis = len(group_data)
    fission_matrix = np.ones((dis,dis))
    for i in range(dis):
        for j in range(dis):
            fission_matrix[i,j] = group_data[i,2] * group_data[j,1]
    return fission_matrix

In [85]:
Create_fission_matrix(group_data)

array([[0.00469938, 0.00196392, 0.00038577, 0.00234969, 0.0077154 ,
        0.00778554, 0.03145779, 0.07508487],
       [0.0055007 , 0.0022988 , 0.00045155, 0.00275035, 0.009031  ,
        0.0091131 , 0.03682185, 0.08788805],
       [0.00319992, 0.00133728, 0.00026268, 0.00159996, 0.0052536 ,
        0.00530136, 0.02142036, 0.05112708],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [75]:
def Create_absorbtion_matrix(group_data):
    dis = len(group_data)
    absorbtion_matrix = np.zeros((dis,dis))
    for i in range(dis):
        absorbtion_matrix[i][i] = group_data[i,0]
    return absorbtion_matrix

In [76]:
Create_absorbtion_matrix(group_data)

array([[0.0056, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.0029, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.0025, 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.0133, 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.0473, 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.018 , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0558, 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1798]])

In [77]:
def Outscattering_matrix(scat_data):
    Outscattering_matrix = np.zeros((len(scat_data),len(scat_data[0])))
    for i in range(len(scat_data)):
        for j in range(len(scat_data.T)):
            if j == i:
                continue
            else:
                Outscattering_matrix[i,i] += scat_data[j,i]
    return Outscattering_matrix

In [78]:
Outscattering_matrix(scat_data)

array([[0.0832, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.1164, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.0788, 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.2019, 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.2056, 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.3257, 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.3612, 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0275]])

In [79]:
def Inscattering_matrix(scat_data):
    Inscattering_matrix = scat_data.copy()
    for i in range(len(scat_data)):
       Inscattering_matrix[i,i] = 0
    return Inscattering_matrix

In [80]:
Inscattering_matrix(scat_data)

array([[0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [5.300e-02, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [3.010e-02, 1.159e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [1.000e-04, 5.000e-04, 7.690e-02, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 1.900e-03, 1.961e-01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 5.000e-03, 1.737e-01, 0.000e+00,
        2.300e-03, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 7.000e-04, 2.460e-02, 2.707e-01,
        0.000e+00, 2.750e-02],
       [0.000e+00, 0.000e+00, 0.000e+00, 1.000e-04, 7.300e-03, 5.500e-02,
        3.589e-01, 0.000e+00]])

In [92]:
k = np.zeros(3)
k[0] = 1
flux = np.zeros((len(scat_data),3))
flux[:,0] = np.ones(len(scat_data))

fission_matrix = Create_fission_matrix(group_data)
absorbtion_matrix = Create_absorbtion_matrix(group_data)
outscattering_matrix = Outscattering_matrix(scat_data)
inscattering_matrix = Inscattering_matrix(scat_data)

mitigation_matrix = absorbtion_matrix + outscattering_matrix - inscattering_matrix

b_matrix = la.inv(mitigation_matrix) @ fission_matrix

eigenvalues, eigenvectors = la.eig(b_matrix)
print(eigenvalues)

[ 0.00000000e+00+0.00000000e+00j  1.09003100e+00+0.00000000e+00j
  2.43595629e-17+1.53722661e-17j  2.43595629e-17-1.53722661e-17j
 -1.27871831e-17+1.25738272e-17j -1.27871831e-17-1.25738272e-17j
 -8.48418492e-19+1.82231485e-18j -8.48418492e-19-1.82231485e-18j]


In [94]:
for i in range(2):
    flux[:,i+1] = (b_matrix @ flux[:,i]) / la.norm(b_matrix @ flux[:,i])
for i in range(2):
    k[i+1] = ((b_matrix @ flux[:,i+1]).T @ flux[:,i+1])/(flux[:,i+1].T @ flux[:,i+1])

In [95]:
print(k)
print(flux)

[1.       1.090031 1.090031]
[[1.         0.26158725 0.26158725]
 [1.         0.3441239  0.3441239 ]
 [1.         0.78197886 0.78197886]
 [1.         0.280355   0.280355  ]
 [1.         0.22326364 0.22326364]
 [1.         0.1176114  0.1176114 ]
 [1.         0.10450765 0.10450765]
 [1.         0.22013644 0.22013644]]
